<?php

/**
 * @file
 * Module file for draggable_form module.
 */

/**
 * Draggable form
 * @{
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 *
 * Show a bit of information about this module on the example page.
 */
function draggable_form_helper($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.draggable_form':
      $table_class_url = Url::fromUri('https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!Element!Table.php/class/Table/9');
      $example_url = Url::fromRoute('draggable_form.description');
      $example_link = Link::fromTextAndUrl(t('Draggble Formoverview page'), $example_url);
      $help_text = '<p>' . t("This module demonstrates how to code a module in order to use Drupal 9's TableDrag theme function.") . '</p>';
      $help_text .= '<h3>' . t('Reference links') . '</h3>';
      $help_text .= '<ul>';
      $help_text .= '<li>' . $table_class_link
        ->toString() . '</li>';
      $help_text .= '<li>' . $table_change_link
        ->toString() . '</li>';
      $help_text .= '<li>' . $attach_change_link
        ->toString() . '</li>';
      $help_text .= '</ul>';
      $help_text .= '<p>' . t('To see this module in action:') . ' ' . $example_link
        ->toString() . '</p>';
      return $help_text;
  }
}
